# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [75]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
irisinfo = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = irisinfo.data

In [0]:
y = irisinfo.target

In [80]:
X.shape

(150, 4)

In [81]:
y.shape

(150,)

## Question 3



```
# This is formatted as code
```

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=1)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(112, 4)
(112,)
(38, 4)
(38,)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
from keras.utils import to_categorical
y_test=to_categorical(y_test, num_classes=3)
y_train=to_categorical(y_train, num_classes=3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [0]:
model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
# Add an input layer  
model.add(Dense(4, activation='sigmoid', input_shape=(4,)))   

# Add an output layer  
model.add(Dense(3, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:

model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [88]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [89]:
history=model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 3ms/sample - loss: 1.1069 - accuracy: 0.4464
Epoch 2/100
112/112 [==============================] - 0s 1ms/sample - loss: 1.0391 - accuracy: 0.6786
Epoch 3/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9970 - accuracy: 0.6875
Epoch 4/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9576 - accuracy: 0.6964
Epoch 5/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.9205 - accuracy: 0.6964
Epoch 6/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8841 - accuracy: 0.7054
Epoch 7/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8500 - accuracy: 0.6964
Epoch 8/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.8160 - accuracy: 0.6964
Epoch 9/100
112/112 [==============================] - 0s 1ms/sample - loss: 0.7831 - accuracy: 0.6964
Epoch 10/100
112/112 [==============================

## Question 10

### Make predictions
- Predict labels on one row

In [90]:
model.predict(X_test[0:1])

array([[0.9643599 , 0.03423262, 0.00140749]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [91]:
y_test[0:1]

array([[1., 0., 0.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [93]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [95]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
price = pd.read_csv('prices.csv')

In [97]:
price.shape

(851264, 7)

In [98]:
price.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [99]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [100]:
price.describe()

open          close            low           high        volume
count  851264.000000  851264.000000  851264.000000  851264.000000  8.512640e+05
mean       70.836986      70.857109      70.118414      71.543476  5.415113e+06
std        83.695876      83.689686      82.877294      84.465504  1.249468e+07
min         0.850000       0.860000       0.830000       0.880000  0.000000e+00
25%        33.840000      33.849998      33.480000      34.189999  1.221500e+06
50%        52.770000      52.799999      52.230000      53.310001  2.476250e+06
75%        79.879997      79.889999      79.110001      80.610001  5.222500e+06
max      1584.439941    1578.130005    1549.939941    1600.930054  8.596434e+08

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [0]:
prices2 = price.drop(['date', 'symbol'], axis=1)
#prices1 = prices1.drop("symbol", axis=1)

In [102]:
prices2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [0]:
prices3 = prices2.head(1000)

In [104]:
prices3.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
# Seperation of features and target column as given above
X = prices3.drop("volume" , axis=1)

y = prices3['volume']

In [106]:
X.shape

(1000, 4)

In [107]:
y.shape

(1000,)

In [108]:
#Normalize label column by dividing it with 1000000
y.describe()

count    1.000000e+03
mean     5.314222e+06
std      1.446565e+07
min      1.000000e+04
25%      8.216250e+05
50%      2.064450e+06
75%      4.620475e+06
max      2.156202e+08
Name: volume, dtype: float64

In [0]:
y1 = y/1000000

In [110]:
y1.describe()

count    1000.000000
mean        5.314222
std        14.465650
min         0.010000
25%         0.821625
50%         2.064450
75%         4.620475
max       215.620200
Name: volume, dtype: float64

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
y2 = y1.to_numpy()

In [112]:
y2.dtype

dtype('float64')

In [0]:
X1 = X.to_numpy()

In [114]:
X1.dtype

dtype('float64')

In [0]:
X1 = np.float32(X1)

In [116]:
X1.dtype

dtype('float32')

In [0]:
y_actual=np.float32(y2)

In [118]:
y_actual.dtype

dtype('float32')

In [119]:
y_actual.shape

(1000,)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
features = tf.math.l2_normalize(X1, axis=None, epsilon=1e-12, name=None)

In [0]:
x = features

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.zeros(shape=(4, 1)) 
b = tf.zeros(shape=(1))

In [123]:
W

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [124]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
@tf.function 
def prediction(features, W, b):
  y_pred = tf.add(tf.matmul(features, W), b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
@tf.function 
def loss(y_actual, y_predicted):
  diff = y_actual - y_predicted
  sqr = tf.square(diff)
  avg = tf.reduce_mean(sqr)
  return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
  # Record mathematical operations on 'tape' to calculate loss
  with tf.GradientTape() as t:
    t.watch([w,b])
    current_prediction = prediction(x, w, b)
    current_loss = loss(y_actual, current_prediction)
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [128]:
for i in range(100):
  W, b = train(x, y_actual, W, b)
  print('Current Training Loss on iteration', i, loss(y_actual, prediction(x, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [129]:
W

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)>

### Observe values of Bias
- Print the updated values

In [130]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([4.607657], dtype=float32)>

In [131]:

b.numpy()

array([4.607657], dtype=float32)

In [132]:
W.numpy()

array([[0.0547828 ],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)